"""complete

Revision ID: ac46d74c1f29
Revises: e94beaef753b
Create Date: 2023-10-30 21:33:19.188717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac46d74c1f29'
down_revision = 'e94beaef753b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_comments_post_id_posts', type_='foreignkey')
        batch_op.drop_column('post_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_comments_post_id_posts', 'posts', ['post_id'], ['id'])

    # ### end Alembic commands ###
