"""done

Revision ID: e69e66116e86
Revises: ac46d74c1f29
Create Date: 2023-10-30 21:41:18.265554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e69e66116e86'
down_revision = 'ac46d74c1f29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_comments_post_id_posts'), 'posts', ['post_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_comments_post_id_posts'), type_='foreignkey')
        batch_op.drop_column('post_id')

    # ### end Alembic commands ###
